### ISSUE TITLE
How know constant value from MASConstraint?

### ISSUE THREAD

**Issue by Fess200** [SnapKit/Masonry#206]

**Comment by cloudkite** [comment]
@Fess200 at the moment this is not supported since MASConstraint can be either a single constraint or a composite constraint ie

```obj-c
//single constraint
this.constraint = make.top.equalTo(10));

//composite constraint
this.constraint = make.top.left.right.equalTo(UIEdgeInsetsMake(10, 15, 20, 50);
```

The recommended approach is to keep track of the constant independently as a variable or const
ie

```objc
self.topOffset = 100;

//later on
make.top.equalTo(self.topOffset));

//then
self.topOffset += 10;

//update constraint
make.top.equalTo(self.topOffset));

```

for an example see https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleUpdateView.m 

however if you want to live dangerously you could cast to a `MASViewConstraint` (if you are sure its a single constraint) and access the private variable `layoutConstant `
