### ISSUE TITLE
Why is Masonry no longer being actively developed?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [SnapKit/Masonry#220]
Hi,

First, thanks so much for your hard work on Masonry and SnapKit - much appreciated!

With respect, I don't understand the decision to put Masonry in a bug fix only state ... I like Masonry and I'm actively using it in a medium-size Objective-C OS X app (20 kloc).  This app was written when Swift was very unstable, so we could not choose Swift and have no plans to convert it to Swift.  So we're left having to convert tons of layout code to SnapKit ... Why not just continue to support Masonry?

There are lots of OS X and iOS devs still actively using Objective-C for lots of projects and it feels like a real loss to the community to lose Masonry and need to convert to SnapKit.  Most of the examples in SnapKit are in Swift and there are lots of us still actively using Objective-C for a variety of good reasons.

Any chance we can "revive" Masonry?  ;-)  Or do you have a "Masonry-to-SnapKit Migration Guide" or assistant?  It would be nice to see both Swift and Objective-C examples in SnapKit.

Anyway, sorry for the whining, I really appreciate you making Masonry and SnapKit available for free.  But I have no plans to convert my app to Swift in the near future and it feels like a big loss to see Masonry relegated to bug fix only ... I'm really bummed out about this.  For large projects, there isn't a huge incentive to convert a bunch of tested and deployed code to SnapKit ... Or is there?

Thanks again for your hard work, and best wishes,

Joel

**Comment by cloudkite** [comment]
Hi Joel,

Thanks for your feedback, I appreciate that the bugfix notice on the readme is a little scary if you have alot Masonry code in your app.

The intention is definitely not to abandon Masonry.  Its really just there to make people aware that the current core maintainers (myself) no longer have time to contribute new features and improvements. This is due mostly to the fact that I'm currently working on web projects. Which means I'm not in the thick of iOS dev, hence I can't dogfood new features or improvements and probably not aware of the latest UIKit API changes or conventions.

However happy to accept improvements and new features in the from of PRs and add new contributors who have a interest in moving Masonry forward and actively maintaining the project. After all being open source anyone can participate and get involved.

Maybe the "bugfix" notice should be changed to a "looking for contributors" notice?

**Comment by cloudkite** [comment]
I think also Masonry on the obj-c side is pretty stable at this point so I don't think it needs as much attention as SnapKit since Swift is changing rapidly between versions and therefore SnapKit needs to keep up with this swift pace.

Props to @robertjpayne who is doing an awesome job of taking up the role of core maintainer on SnapKit and keeping it up to date with the newest versions of Swift

**Comment by robertjpayne** [comment]
@iosdev-republicofapps we're definitely not "dropping" Masonry support, if we find/hear about bugs we'll definitely fix em. 

As far as new features, we'll try and ensure it supports any new layout attributes etc… but it won't be getting any sort of new composite features that would be the library better since as @cloudkite mentioned he's been out of the iOS dev world and I'm focusing any new feature development efforts into the Swift library.

**Comment by iosdev-republicofapps** [comment]
Thanks!  Sorry, I didn't mean to sound like a whiner and I appreciate all of your hard work.  I was just concerned, that's all.

If you need any help maintaining Objective-C Masonry, I'd be happy to help as best I can.

Thanks!
