### ISSUE TITLE
User sizeToFit For UILabel

### ISSUE THREAD

**Issue by seanLee** [SnapKit/Masonry#228]
I use ````sizeToFit```` to make UILabel resize and just make constraint of the origin,there is no information print in the console.So can I use in this way?

**Comment by robertjpayne** [comment]
@seanLee once you use auto layout you the autolayout engine will take full control of your dimensions and origins thus sizeToFit is not going to do you much good.

You'll want to constrain it to a width and a height ( or a max height via lessThanOrEqualTo ).

**Comment by seanLee** [comment]
ok~I will change the use of the library.Thx very much

**Comment by mysteriouss** [comment]
Is there a way to constraint the size.height of UILabel to its own?

 e.g. I want to increase the height of UILabel by some pixels after the Auto-Layout Engine does its work. The reason is that I was using a third-party font and the emoji text at the first line of UILabel  was cutting off the head..So I've got to increase the height. And I've got several lines of text in UILabel, fixed height is not my option.

**Comment by seanLee** [comment]
@mysteriouss  u can calculator the size of the UILabel and remake the constraint.But if u find the way that can make what u want,please tell me,thx very much~

**Comment by robertjpayne** [comment]
The main reason text labels don't "expand" is probably because you need to tweak the `content compression priority` or `content hugging priorities`.

Have a look in the docs for `setContentCompression*` and `setContentHugging` on UIView, they can help ensure labels don't get clipped content.
