### ISSUE TITLE
Animate can`t be executed On iOS 9

### ISSUE THREAD

**Issue by dengbin9009** [SnapKit/Masonry#243]
Hi,

   First of all, i love this library. I use it everyday and it makes Auto-Layout so much less painful.

```javascript
[UIView animateWithDuration:kSelectedImageViewMoveToIndexAnimateDuration animations:^{
        [_selectedImageView mas_updateConstraints:^(MASConstraintMaker *make) {
            make.left.equalTo(weakSelf).offset(index*_selectedImageView.frame.size.width);
        }];
        if (animated) {
            [_selectedImageView layoutIfNeeded];
        }
    } completion:^(BOOL finished) {
        [self changeTitleLabelStateToSelectedAtIndex:index];
    }];
```
 animate can be executed On iOS 8
but it is Invalid  On iOS 9

**Comment by dengbin9009** [comment]
No one is the same as me?

**Comment by robertjpayne** [comment]
@dengbin9009 you need to call `layoutIfNeeded` on the view the constraints are installed on rather than the view the constraints are made for.

This is the closest common superview for each constraint, so you kind of have to use your best judgement to determine which is the furthest for any constraints.

You likely just need to do `[weakSelf layoutIfNeeded]` in this case.

**Comment by dengbin9009** [comment]
thx so much!  It solved my problem.
But it work On iOS 8 and iOS 7,So I didn't pay attention to the problem。

**Comment by robertjpayne** [comment]
No worries!
