### ISSUE TITLE
Why not exposing underlying `layoutConstraint`?

### ISSUE THREAD

**Issue by huguesbr** [SnapKit/Masonry#306]
I notice that `MASViewConstraint` has a `private` property `layoutConstraint` which return the underlying `NSLayoutConstraint`. Why not exposing it directly?

I'm working with another framework ([JazzHands](https://github.com/IFTTT/JazzHands)) which require to pass it a `NSLayoutConstraint` to be animated.

I'm using KVC to access the constraint, but it for sure pretty fragile:
    [mas_calendarVerticalConstraint valueForKey:@"layoutConstraint"];

So any specific why I should not do this and then for why is not directly exposed?

I see `Masonry` (and may be wrong) more like a constraint builder not like a constraint "replacement"

Thanks

**Comment by robertjpayne** [comment]
@huguesbr we don't really want people manipulating these because it more likely than not will cause issues with updating/remaking etc… You can continue doing what you are doing though if need be.

We recommend people fallback to the regular old API if they need to make constraints that play nice with other frameworks.

**Comment by huguesbr** [comment]
@robertjpayne got it, thx
