### ISSUE TITLE
Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by gityoung** [SnapKit/Masonry#349]
Unable to simultaneously satisfy constraints.？

**Comment by robertjpayne** [comment]
@gityoung issue reports like this are extremely unproductive and disrespectful to the owners/contributors that freely use their spare time to address open issues. 

Please when you open issues on open source repo's include as much information as possible and clearly  lay out what your issue is and the expected behaviour you think you should be seeing.
