### ISSUE TITLE
About memory reveal

### ISSUE THREAD

**Issue by dengbin9009** [SnapKit/Masonry#366]
Why I use `Self` in block  will not cause memory reveal?
For example:
```
[self.button remakeConstraints:^(MASConstraintMaker *make) {
        make.width.equalTo(@(self.buttonSize.width));
        make.height.equalTo(@(self.buttonSize.height));
}];
```
Please Help me, thx！

**Comment by yolii** [comment]
answer in stackoverflow. http://stackoverflow.com/questions/34914834/when-should-i-use-weakself-in-a-block-and-why-there-is-no-retain-cycle-in-mason

**Comment by wangch6688** [comment]
Maybe It`s because you use a [strong] self in a block, block will retain object once,i can give you a simple demo, i hope i can help you[😊]

demo:


 __weak __typeof(self)weakSelf = self;

[self.button remakeConstraints:^(MASConstraintMaker *make) {

    __strong __typeof(weakSelf)strongSelf = weakSelf;
        make.width.equalTo(@(strongSelf.buttonSize.width));
        make.height.equalTo(@(strongSelf.buttonSize.height));
}];



________________________________
发件人: FlyingChickenWings <notifications@github.com>
发送时间: 2016年7月26日 9:30:37
收件人: SnapKit/Masonry
主题: [SnapKit/Masonry] About memory reveal (#366)


Why I use Self in block will not case memory reveal?
For example:

[self.button remakeConstraints:^(MASConstraintMaker *make) {
        make.width.equalTo(@(self.buttonSize.width));
        make.height.equalTo(@(self.buttonSize.height));
}];


Please Help me, thx！

**Comment by wangch6688** [comment]
[SnapKit/Masonry] About memory reveal (#366)
王 闯闯
|
今天 11:13
Maybe It`s because you use a [strong] self in a block, block will retain object once,i can give you a simple demo, i hope i can help you[cid:f9ec2dcb-d4bf-4fb4-b9ae-a2d887e9cab7]

demo:


 __weak __typeof(self)weakSelf = self;


[self.button remakeConstraints:^(MASConstraintMaker *make) {

    __strong __typeof(weakSelf)strongSelf = weakSelf;
        make.width.equalTo(@(strongSelf.buttonSize.width));
        make.height.equalTo(@(strongSelf.buttonSize.height));
}];


________________________________
发件人: FlyingChickenWings <notifications@github.com>
发送时间: 2016年7月26日 9:30:37
收件人: SnapKit/Masonry
主题: [SnapKit/Masonry] About memory reveal (#366)


Why I use Self in block will not case memory reveal?
For example:

[self.button remakeConstraints:^(MASConstraintMaker *make) {
        make.width.equalTo(@(self.buttonSize.width));
        make.height.equalTo(@(self.buttonSize.height));
}];


Please Help me, thx！

―

**Comment by robertjpayne** [comment]
@dengbin9009 The `make/remake/update` closures used in Masonry are not retained and are immediately executed. Thus you do not need to worry about retain cycles.
